server:
  port: 8082


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://39.100.49.60:3306/licly_micro_service?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 902116
  redis:
    port: 6379
    host: 39.100.49.60
    password: wsxzaq.

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
